name: CTF Registration
on:
  issue_comment:
    types: [created]

jobs: 
  ctf_registration:
    runs-on: ubuntu-latest
    if: startsWith(github.event.comment.body, '/join')
    steps:
      - name: Register player
        uses: actions/github-script@v6
        env:
          LOGIN: ${{ github.event.comment.user.login }}
        with:
          github-token: ${{ secrets.ADMIN_TOKEN }}
          script: |
            if (context.issue.number === 1) {

              console.log('%s wants to join the class!', process.env.LOGIN);

              console.log('Creating player repo ...');

              await github.rest.repos.createUsingTemplate({
                template_owner: 'Octoversity',
                template_repo: 'grading-private',
                name: `grading-${process.env.LOGIN}`,
                owner: 'Octoversity',
                private: false
              });
              
              console.log('Pausing to allow repository to finish creation ...');
              function freeze(time) {
                const stop = new Date().getTime() + time;
                while(new Date().getTime() < stop);       
              }
              freeze(10000);
              console.log("Done waiting ...");
              
              console.log('Adding branch protection rules ...');
              
              await github.rest.repos.updateBranchProtection({
                owner: 'Octoversity',
                repo: `grading-${process.env.LOGIN}`,
                branch: 'main',
                required_status_checks: null,
                enforce_admins: true,
                required_pull_request_reviews: {"dismissal_restrictions": {"users":[], "teams":[]}, "dismiss_stale_reviews": false, "require_code_owner_reviews": false, "required_approving_review_count": 1},
                restrictions: null
              });
              
              console.log('Creating environment ...');
              
              await github.rest.repos.createOrUpdateEnvironment({
                owner: 'Octoversity',
                repo: `grading-${process.env.LOGIN}`,
                environment_name: "CTF",
                deployment_branch_policy: {"protected_branches": true, "custom_branch_policies": false}
              });

            }
            
      - name: Generating & encrypting flag
        env:
          LOGIN: ${{ github.event.comment.user.login }}
        uses: maclarel/actions-set-secret@v/1.9.9
        with:
          name: 'FLAG'
          value: ${{ secrets.FLAG }}
          repository: "Octoversity/grading-${{ env.LOGIN }}"
          token: ${{ secrets.ADMIN_TOKEN }}
          environment: 'CTF'
          
      - name: Change visibility & Add player
        uses: actions/github-script@v6
        env:
          LOGIN: ${{ github.event.comment.user.login }}
        with:
          github-token: ${{ secrets.ADMIN_TOKEN }}
          script: |
            if (context.issue.number === 1) {
              
              console.log('Change repository visibility ...');
              
              await github.rest.repos.update({
                owner: 'Octoversity',
                repo: `grading-${process.env.LOGIN}`,
                private: true
              });
              
              console.log('Adding player as collaborator ...');

              await github.rest.repos.addCollaborator({
                owner: 'Octoversity',
                repo: `grading-${process.env.LOGIN}`,
                username: process.env.LOGIN,
                permission: 'push'
              });
              
            }
          
